### ISSUE TITLE
add latex support!

### ISSUE THREAD

**Issue by alex180500** [nxht/one-monokai-python#1]
Please add better support for latex like in https://github.com/azemoh/vscode-one-monokai

This is how it looks right now:
<img width="260" alt="image" src="https://github.com/nxht/one-monokai-python/assets/30732244/0907d117-2d87-447d-a06e-d60c065b708c">

This is how it looks in vscode one monokai
<img width="324" alt="image" src="https://github.com/nxht/one-monokai-python/assets/30732244/99029faf-2814-4a61-a31e-b0e3055f49e0">

**Comment by nxht** [comment]
@alex180500 
Sorry for the delay. I didn't even know if the issue was created until now.

The color for latex case was removed unintentionally during adding highlighting support for typescript decorator. 

I've restored the color for latex case. Though it's more of a temporary solution, but should be working as expected.
